// Package v1alpha1 has the kuben.dev/v1alpha1 custom resources: the Go
// counterpart of the Rust crate crates/kuben-crd (lib.rs and src/v1alpha1).
//
// The JSON of every type is the wire form the Rust types read and wrote
// (serde field names, defaults applied on decode, skip rules on encode), and
// charts/kuben/crds/kuben.dev_all.yaml stays the source of the CRD manifest
// until 2.1; the tests pin both. Kubernetes API conventions apply here
// rather than the rest of the Go code base's: optional fields are pointers
// or omitempty slices, objects embed metav1.TypeMeta and metav1.ObjectMeta,
// and DeepCopy is generated by controller-gen.
//
// +kubebuilder:object:generate=true
// +groupName=kuben.dev
package v1alpha1

//go:generate go tool controller-gen object paths=./...
