/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit log of the caller's organization(s). */
        get: operations["listAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with email + password. Sets an `HttpOnly` session cookie.
         *     Repeated failures are throttled (`429` with `Retry-After`).
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out: revoke the current session and clear the cookie. */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/healthz/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-subsystem health (authenticated). */
        get: operations["getHealthDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated user. */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replace the caller's password. Every other session is signed out. */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Members of the caller's organization. */
        get: operations["listMembers"];
        put?: never;
        /** Invite a member. New accounts get a one-time temporary password. */
        post: operations["inviteMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{member}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a member: bindings, sessions and tokens are revoked immediately. */
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        /** Change a member's role. */
        patch: operations["updateMember"];
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects visible to the caller. */
        get: operations["listProjects"];
        put?: never;
        /** Create a project (writes a `Project` CR). */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One project. */
        get: operations["getProject"];
        put?: never;
        post?: never;
        /**
         * Delete an empty project. Projects with environments are refused (`409`):
         *     deleting environments is an explicit, per-environment decision.
         */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a project's environments. */
        get: operations["listEnvironments"];
        put?: never;
        /** Create an environment (the controller provisions its namespace). */
        post: operations["createEnvironment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/environments/{environment}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One environment. */
        get: operations["getEnvironment"];
        put?: never;
        post?: never;
        /**
         * Delete an environment. Production environments need the
         *     `env-delete-protected` permission and are purged after a grace period.
         */
        delete: operations["deleteEnvironment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/environments/{environment}/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the apps of an environment. */
        get: operations["listApps"];
        put?: never;
        /** Deploy a new app from a container image. */
        post: operations["createApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/environments/{environment}/apps/{app}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * App detail with pods. Plain env values are included only for callers
         *     holding `secret-read`.
         */
        get: operations["getApp"];
        put?: never;
        post?: never;
        /**
         * Delete an app and everything it owns. Volumes are kept unless
         *     `delete_volumes=true`.
         */
        delete: operations["deleteApp"];
        options?: never;
        head?: never;
        /**
         * Update an app (image changes require `app-deploy`). Every change is a
         *     new release revision.
         */
        patch: operations["updateApp"];
        trace?: never;
    };
    "/api/v1/projects/{project}/environments/{environment}/apps/{app}/domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check that every hostname of the app points at the gateway. */
        get: operations["checkAppDomains"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/environments/{environment}/apps/{app}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent log lines of the app's pods (at most 10 pods). */
        get: operations["getAppLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/environments/{environment}/apps/{app}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Promote the app to another environment of the same project. */
        post: operations["promoteApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/environments/{environment}/apps/{app}/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Release history, newest first (50 revisions). */
        get: operations["listReleases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/environments/{environment}/apps/{app}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rolling restart of every process (no spec change). */
        post: operations["restartApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/environments/{environment}/apps/{app}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Roll back to an earlier revision (recorded as a new revision). */
        post: operations["rollbackApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/environments/{environment}/apps/{app}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a scheduled process now (a Job from its CronJob template). */
        post: operations["runApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/environments/{environment}/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the secrets of an environment (names and keys). */
        get: operations["listSecrets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/environments/{environment}/secrets/{secret}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Create or replace a secret. */
        put: operations["putSecret"];
        post?: never;
        /** Delete a secret created through Kuben. */
        delete: operations["deleteSecret"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/environments/{environment}/templates/{template}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deploy a template into an environment. */
        post: operations["deployTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether the first admin account still has to be created. */
        get: operations["setupStatus"];
        put?: never;
        /** Create the organization and its first admin (owner), and sign in. */
        post: operations["setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The template catalogue. */
        get: operations["listTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's API tokens. */
        get: operations["listTokens"];
        put?: never;
        /** Create a personal API token. */
        post: operations["createToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tokens/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke one of the caller's tokens (immediately effective). */
        delete: operations["revokeToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        AppDetail: {
            app: components["schemas"]["AppDto"];
            pods: components["schemas"]["PodDto"][];
        };
        AppDto: {
            name: string;
            project: string;
            /** @description Environment short name. */
            environment: string;
            namespace: string;
            image?: string | null;
            git_repo?: string | null;
            url?: string | null;
            ready: boolean;
            /** @description `Available`, `Progressing`, `RolloutFailed`, `Scheduled`, `AwaitingBuild`, ... */
            reason?: string | null;
            message?: string | null;
            processes: components["schemas"]["ProcessDto"][];
            /** @description Values are only included in the app detail, for callers allowed to read secrets. */
            env: components["schemas"]["EnvVarDto"][];
            domains: string[];
            volumes: components["schemas"]["VolumeDto"][];
            created_at?: string | null;
        };
        AuditEventDto: {
            /** Format: int64 */
            seq: number;
            id: string;
            /**
             * Format: int64
             * @description Unix milliseconds.
             */
            at: number;
            /** @description `session`, `token`, `user` or `anonymous`. */
            actor_kind: string;
            /** @description Email of the actor (or its id if the user no longer exists). */
            actor?: string | null;
            /** @description OpenAPI operation id, e.g. `createApp`. */
            action: string;
            target_kind?: string | null;
            target?: string | null;
            /** @description `success`, `denied`, `failure`, `throttled` or `error`. */
            outcome: string;
            /** Format: int32 */
            status?: number | null;
            ip?: string | null;
            request_id?: string | null;
        };
        AuditPage: {
            events: components["schemas"]["AuditEventDto"][];
            /**
             * Format: int64
             * @description Pass as `before` to fetch the next (older) page.
             */
            next_before?: number | null;
        };
        ChangePassword: {
            /** Format: password */
            current_password: string;
            /** Format: password */
            new_password: string;
        };
        CreateApp: {
            /** @example api */
            name: string;
            /** @example ghcr.io/acme/api:1.4.2 */
            image: string;
            /**
             * Format: int32
             * @description Port the process listens on; omit for workers and scheduled jobs.
             * @example 8080
             */
            port?: number | null;
            command?: string[];
            /** Format: int32 */
            replicas?: number;
            /**
             * Format: int32
             * @description CPU autoscaling up to this many replicas when greater than `replicas`.
             */
            max_replicas?: number | null;
            /**
             * @description Size preset: `nano`, `small`, `medium`, `large` (or custom).
             * @example small
             */
            size?: string;
            env?: components["schemas"]["EnvVarDto"][];
            domains?: string[];
            /** @example /healthz */
            health_check_path?: string | null;
            /**
             * @description Cron expression: the app runs as a scheduled job (no port).
             * @example 0 3 * * *
             */
            schedule?: string | null;
            /**
             * @description IANA time zone for `schedule` (default UTC).
             * @example Europe/Berlin
             */
            time_zone?: string | null;
            protocol?: components["schemas"]["ProtocolDto"];
            volumes?: components["schemas"]["VolumeDto"][];
            /**
             * Format: int64
             * @description Group id owning the volumes, for images running as a non-root user.
             * @example 1000
             */
            fs_group?: number | null;
        };
        CreateEnvironment: {
            /**
             * @description Short name, e.g. `prod` (the object is named `<project>-<name>`).
             * @example prod
             */
            name: string;
            env_type?: components["schemas"]["EnvType"];
            quota?: null | components["schemas"]["QuotaInput"];
        };
        CreateProject: {
            /**
             * @description DNS label, e.g. `shop` (at most 40 characters).
             * @example shop
             */
            name: string;
            /** @example Online Shop */
            display_name: string;
            description?: string | null;
        };
        CreateToken: {
            /** @example github-actions */
            name: string;
            /**
             * @description Upper bound on what the token may do: `viewer`, `developer` or `admin`.
             * @example developer
             */
            role?: string;
            /**
             * @description Restrict the token to one project.
             * @example shop
             */
            project?: string | null;
            /**
             * @description Restrict the token to one environment of `project`.
             * @example staging
             */
            environment?: string | null;
            /**
             * Format: int32
             * @description Lifetime in days (1–365, default 90).
             */
            expires_in_days?: number | null;
        };
        CreatedToken: {
            /** @description The token itself. Shown exactly once; only its hash is stored. */
            token: string;
            info: components["schemas"]["TokenDto"];
        };
        DeployTemplate: {
            /**
             * @description App name (also the in-cluster hostname of TCP services).
             * @example db
             */
            name: string;
        };
        DeployedTemplate: {
            app: components["schemas"]["AppDto"];
            /** @description Secret with the generated credentials, e.g. `db-credentials`. */
            credentials_secret: string;
            /** @description Reference it from other apps as `KEY=@<secret>/<key>`. */
            connection_keys: string[];
        };
        DomainCheck: {
            host: string;
            /** @description Addresses the host currently resolves to. */
            addresses: string[];
            /** @description Addresses of the gateway. */
            expected: string[];
            /** @description `ok`, `mismatch`, `unresolved` or `unknown`. */
            status: string;
            message: string;
        };
        /** @enum {string} */
        EnvType: "standard" | "production" | "preview";
        /** @description Environment variable: a plain `value` or a `secret` reference. */
        EnvVarDto: {
            /** @example LOG_LEVEL */
            name: string;
            value?: string | null;
            secret?: null | components["schemas"]["SecretRef"];
        };
        EnvironmentDto: {
            /** @description Short name used in URLs, e.g. `prod`. */
            name: string;
            /** @description Kubernetes object name, e.g. `shop-prod`. */
            resource_name: string;
            project: string;
            /** @description `standard`, `production` or `preview`. */
            env_type: string;
            namespace: string;
            /** @description `Pending`, `Ready`, `Terminating` or `Degraded`. */
            phase?: string | null;
            ready: boolean;
            message?: string | null;
            deleting: boolean;
            /** @description When a soft-deleted environment will be purged. */
            deletion_scheduled_at?: string | null;
            created_at?: string | null;
        };
        HealthDetails: {
            ready: boolean;
            database: string;
            cluster: boolean;
            /** Format: int64 */
            seq: number;
            pods: number;
            subsystems: Record<string, never>;
        };
        InviteMember: {
            /** @example carol@example.com */
            email: string;
            display_name?: string | null;
            /** @description `viewer`, `developer`, `admin` or `owner`. */
            role?: string;
        };
        InvitedMember: {
            member: components["schemas"]["MemberDto"];
            /**
             * @description Temporary password for a newly created account. Shown once; it must be
             *     replaced at the first login. `null` when the user already existed.
             */
            temporary_password?: string | null;
        };
        JobStarted: {
            job: string;
        };
        LoginRequest: {
            /** @example admin@kuben.local */
            email: string;
            /**
             * Format: password
             * @example correct horse battery staple
             */
            password: string;
        };
        MemberDto: {
            id: string;
            email: string;
            display_name?: string | null;
            role: string;
            /** @description Invited and has not replaced the temporary password yet. */
            must_change_password: boolean;
            active: boolean;
        };
        PodDto: {
            name: string;
            process?: string | null;
            /** @description `pending`, `running`, `succeeded`, `failed` or `unknown`. */
            phase: string;
            ready: boolean;
            /** Format: int32 */
            restarts: number;
            reason?: string | null;
            node?: string | null;
            started_at?: string | null;
        };
        PodLogs: {
            pod: string;
            process?: string | null;
            lines: string[];
            /** @description Why no logs could be read (e.g. the container is still starting). */
            error?: string | null;
        };
        /** @description Problem Details body. */
        Problem: {
            /**
             * @description Stable machine-readable code, e.g. `forbidden`.
             * @example forbidden
             */
            code: string;
            /** @description Short human readable title. */
            title: string;
            /**
             * Format: int32
             * @description HTTP status.
             */
            status: number;
            /** @description Details, if safe to expose. */
            detail?: string | null;
        };
        ProcessDto: {
            name: string;
            command: string[];
            /** Format: int32 */
            port?: number | null;
            size: string;
            /** Format: int32 */
            min_replicas: number;
            /** Format: int32 */
            max_replicas: number;
            /** @description Cron expression of scheduled processes. */
            schedule?: string | null;
            /** @description `http` or `tcp`. */
            protocol: string;
        };
        ProjectDto: {
            name: string;
            uid?: string | null;
            display_name: string;
            description?: string | null;
            org?: string | null;
            /** Format: int32 */
            environments: number;
            ready: boolean;
            deleting: boolean;
            created_at?: string | null;
        };
        Promote: {
            /**
             * @description Target environment (short name) in the same project.
             * @example production
             */
            to_environment: string;
            /** @description Only report what would change. */
            dry_run?: boolean;
        };
        PromoteResult: {
            dry_run: boolean;
            /** @description The app did not exist in the target and was (or would be) created. */
            created: boolean;
            /** @description Human-readable diff; values of environment variables are never shown. */
            changes: string[];
            /** @description E.g. secrets referenced by the app that are missing in the target. */
            warnings: string[];
            app?: null | components["schemas"]["AppDto"];
        };
        /** @enum {string} */
        ProtocolDto: "http" | "tcp";
        PutSecret: {
            /** @description Key → UTF-8 value. Replaces the whole secret. */
            data: {
                [key: string]: string;
            };
        };
        QuotaInput: {
            /** @example 4 */
            cpu?: string | null;
            /** @example 8Gi */
            memory?: string | null;
            /**
             * Format: int32
             * @example 50
             */
            pods?: number | null;
        };
        ReleaseDto: {
            /** Format: int64 */
            revision: number;
            image?: string | null;
            /** @description `create`, `deploy`, `config`, `rollback`, `promote` or `template`. */
            reason: string;
            note?: string | null;
            /** @description Email of whoever made the change. */
            actor?: string | null;
            /** Format: int64 */
            created_at: number;
            /** @description The newest revision (what should be running). */
            current: boolean;
        };
        Rollback: {
            /**
             * Format: int64
             * @description Revision to restore.
             */
            revision: number;
        };
        RunJob: {
            /** @description Scheduled process to run (default: the first one). */
            process?: string | null;
        };
        SecretDto: {
            name: string;
            /** @description Key names only; values are never returned. */
            keys: string[];
            created_at?: string | null;
        };
        SecretRef: {
            name: string;
            key: string;
        };
        SetupRequest: {
            /** @example ACME */
            org_name: string;
            /** @example you@example.com */
            email: string;
            /** Format: password */
            password: string;
            /** @description The setup token from the installer's link, when required. */
            token?: string | null;
        };
        SetupStatus: {
            /** @description No admin account exists yet; the console shows `/setup`. */
            needed: boolean;
            /** @description `POST /setup` must carry the token the installer printed. */
            token_required: boolean;
        };
        TemplateDto: {
            id: string;
            name: string;
            description: string;
            category: string;
            image: string;
            /** Format: int32 */
            port: number;
            /** @description `http` (public route) or `tcp` (cluster-internal). */
            protocol: string;
            /** @description `mountPath (size)` of each volume. */
            volumes: string[];
            /** @description Keys of the `<app>-credentials` secret, e.g. `url`. */
            connection_keys: string[];
        };
        TokenDto: {
            id: string;
            name: string;
            /** @description Non-secret prefix to recognise the token, e.g. `kbn_pat_0192f3a1`. */
            prefix: string;
            role: string;
            project?: string | null;
            environment?: string | null;
            /** Format: int64 */
            expires_at?: number | null;
            /** Format: int64 */
            last_used_at?: number | null;
            revoked: boolean;
            /** Format: int64 */
            created_at: number;
        };
        /** @description Partial update; omitted fields are left unchanged, lists are replaced. */
        UpdateApp: {
            image?: string | null;
            /** Format: int32 */
            port?: number | null;
            command?: string[] | null;
            /** Format: int32 */
            replicas?: number | null;
            /** Format: int32 */
            max_replicas?: number | null;
            size?: string | null;
            env?: components["schemas"]["EnvVarDto"][] | null;
            domains?: string[] | null;
            /** @description Empty string removes the health check. */
            health_check_path?: string | null;
            /** @description Empty string removes the schedule. */
            schedule?: string | null;
            time_zone?: string | null;
            protocol?: null | components["schemas"]["ProtocolDto"];
            /** @description Replaces the list. Removed volumes are unmounted, never deleted. */
            volumes?: components["schemas"]["VolumeDto"][] | null;
            /**
             * Format: int64
             * @description `0` removes the fsGroup.
             */
            fs_group?: number | null;
        };
        UpdateMember: {
            role: string;
        };
        UserDto: {
            id: string;
            email: string;
            display_name?: string | null;
            /** @description How the request was authenticated: `session` or `token`. */
            via: string;
            /**
             * @description The temporary password must be replaced (`POST /me/password`) before
             *     anything else is allowed.
             */
            must_change_password: boolean;
        };
        /** @description Persistent volume (kept when the app is deleted, unless requested). */
        VolumeDto: {
            /** @example data */
            name: string;
            /** @example /data */
            mount_path: string;
            /**
             * @description Capacity such as `5Gi`. Can grow, never shrink.
             * @example 5Gi
             */
            size?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    listAudit: {
        parameters: {
            query?: {
                /** @description Page size (1–200, default 50). */
                limit?: number;
                /** @description `next_before` of the previous page. */
                before?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Bad credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Too many failed attempts */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getHealthDetails: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDetails"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePassword"];
            };
        };
        responses: {
            /** @description Password changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberDto"][];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    inviteMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteMember"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitedMember"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User id */
                member: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updateMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User id */
                member: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMember"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberDto"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDto"][];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProject"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDto"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description No cluster configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description The project still has environments */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listEnvironments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentDto"][];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEnvironment"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentDto"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description No cluster configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Environment short name */
                environment: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Environment short name */
                environment: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletion accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listApps: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Environment short name */
                environment: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppDto"][];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Environment short name */
                environment: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApp"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppDto"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Environment short name */
                environment: string;
                /** @description App name */
                app: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppDetail"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteApp: {
        parameters: {
            query?: {
                /** @description Also delete the app's persistent volumes. Irreversible. */
                delete_volumes?: boolean;
            };
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Environment short name */
                environment: string;
                /** @description App name */
                app: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updateApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Environment short name */
                environment: string;
                /** @description App name */
                app: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateApp"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppDto"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    checkAppDomains: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Environment short name */
                environment: string;
                /** @description App name */
                app: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainCheck"][];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getAppLogs: {
        parameters: {
            query?: {
                /** @description Lines per pod (1–2000, default 200). */
                tail?: number;
                /** @description Only pods of this process. */
                process?: string;
                /** @description Logs of the previous (crashed) container instance. */
                previous?: boolean;
            };
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Environment short name */
                environment: string;
                /** @description App name */
                app: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PodLogs"][];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    promoteApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Environment short name (source) */
                environment: string;
                /** @description App name */
                app: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Promote"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromoteResult"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listReleases: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Environment short name */
                environment: string;
                /** @description App name */
                app: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseDto"][];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    restartApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Environment short name */
                environment: string;
                /** @description App name */
                app: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restart scheduled */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    rollbackApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Environment short name */
                environment: string;
                /** @description App name */
                app: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Rollback"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppDto"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    runApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Environment short name */
                environment: string;
                /** @description App name */
                app: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunJob"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStarted"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listSecrets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Environment short name */
                environment: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretDto"][];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    putSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Environment short name */
                environment: string;
                /** @description Secret name */
                secret: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutSecret"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretDto"];
                };
            };
            /** @description A secret with this name exists and is not managed by Kuben */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Environment short name */
                environment: string;
                /** @description Secret name */
                secret: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deployTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Environment short name */
                environment: string;
                /** @description Template id */
                template: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeployTemplate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeployedTemplate"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    setupStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
        };
    };
    setup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Admin created and signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Missing, wrong or expired setup token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Setup is already complete */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateDto"][];
                };
            };
        };
    };
    listTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenDto"][];
                };
            };
        };
    };
    createToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateToken"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedToken"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    revokeToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Token id */
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
